### ISSUE TITLE
Setup CI that automatically publishes some example IP

### ISSUE THREAD

**Issue by mithro** [idea-fasoc/OpenFASOC#1]
It would be good to setup a CI system which automatically publishes some IP to a repository as part of the skywater-pdk.

Once you have it all working, we can probably create a https://foss-eda-tools.googlesource.com/skywater-pdk/ip/sky130_fasoc_ip_tempsensor/ repository.

**Comment by msaligane** [comment]
@saicharan0112 and @luccareinehr I think we need to discuss how to do this. We have everything now to this.

**Comment by saicharan0112** [comment]
I don't find any reference IPs that are published under this URL (at least
not publicly available). Do you happen to have any such?

**Comment by saicharan0112** [comment]
I don't think this is relevant anymore. I neither see any IPs under that link and nor open the link https://foss-eda-tools.googlesource.com/skywater-pdk/ip/. Maybe we can have any example on how other IPs are backed? Is this for having a IP database similar to opencores?
