### ISSUE TITLE
docs: notebooks are generating files already present in the repository

### ISSUE THREAD

**Issue by luccareinehr** [idea-fasoc/OpenFASOC#103]
When running [temp_sense_genCollab.ipynb](https://github.com/idea-fasoc/OpenFASOC/blob/main/docs/source/notebooks/temp_sense_genCollab.ipynb), the whole repo is getting copied again in the `docs/notebook/` folder. This notebook also uses auxiliary files ([aux_files/](https://github.com/idea-fasoc/OpenFASOC/tree/main/docs/source/notebooks/aux_files)) that are already present in the repo cloned originally by the user.

We should assume that the user has cloned OpenFASoC, has successfully installed all dependencies and is running the notebook inside the clone, just like it is done in notebooks from Python projects ([example](https://scikit-learn.org/stable/auto_examples/classification/plot_lda_qda.html#sphx-glr-auto-examples-classification-plot-lda-qda-py)). The [installation docs ](https://openfasoc.readthedocs.io/en/latest/getting-started.html#run-openfasoc-flow) already has a section for the user to test its installation (which could be improved).

Thus: 

1. The notebooks don't have to re-install everything at the beginning.
2. Any file used by the notebook should be taken directly from the repository itself (and not re-copy it).

**Comment by alibillalhammoud** [comment]
@luccareinehr 
On (1) it is not necessarily true that the user has cloned the repo. Using the collab link, It is possible to launch the notebook directly into a cloud based collab env or share the notebook with the link. 
On (2) I agree. I can make a PR to remove some unnecessary copies of files. As you said before, the repo is already very large.
