### ISSUE TITLE
tempsense: lvs stopped working after openroad pull #2289

### ISSUE THREAD

**Issue by luccareinehr** [idea-fasoc/OpenFASOC#109]
https://github.com/The-OpenROAD-Project/OpenROAD/pull/2289/files

To do:

- [x] Modify pdngen to pdn.tcl #81 
- [x] Fix route not getting created from header cells to VIN
- [x] Check if LVS is now not giving mismatches

**Comment by saicharan0112** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD/pull/2289 - To track from the openroad repo side.

**Comment by luccareinehr** [comment]
A note to myself: LVS won't work if make is run from ORFS flow/Makefile. It needs to be run from OpenFASOC's tempsense Makefile

**Comment by luccareinehr** [comment]
To [document the flow](https://openfasoc.readthedocs.io/en/latest/flow-tempsense.html#rtl-to-gds-flow) after #87, it was basically needed to (re)create a second net (r_VIN) that makes the route from the ring, the net's block terminal (BTerm), to the HEADER cells.

Otherwise, if we just tweaked the original VIN net, all instances in the stdcell grid would get routed to it...
