### ISSUE TITLE
tempsense: fail run when it encounters LVS errors

### ISSUE THREAD

**Issue by luccareinehr** [idea-fasoc/OpenFASOC#114]
For some types of LVS errors, `netgen` does not exit with `return code 1` and the temp-sense-gen still says that "LVS is clean!" when it is not.

For example:
![image](https://user-images.githubusercontent.com/75084099/196530281-dbf94e6a-320a-424e-88fd-ebc7720afbe8.png)

Here I highlight the line printed by netgen that's attesting the LVS error. Notice how at the end of the generator run it still says that there was no error.

That is also the reason why sometimes the temp-sense-gen CI doesn't fail even with some LVS mismatches.

**Comment by saicharan0112** [comment]
@luccareinehr good one! So we need an effective lvs report parser?

**Comment by saicharan0112** [comment]
Or should this be diverted to Tim Edwards to take care of this inside Netgen itself?

**Comment by luccareinehr** [comment]
@saicharan0112 Good idea, ideally it should be changed in netgen. If they disagree then we can make a parser

**Comment by saicharan0112** [comment]
@luccareinehr is this still seen in the lvs report? Can we provide the testcase by packing the latest netlists to Tim Edwards to ask if he can take care of this inside Netgen?

**Comment by msaligane** [comment]
@luccareinehr is this ready to close?

**Comment by saicharan0112** [comment]
@luccareinehr Its just that the report parser python script present inside the tools directory has hardcoded lvs error message. I just modified it to catch any type of "fail" messages. Not sure if you had any conversation with Tim Edwards on this.

Happy New year BTW ;)
