### ISSUE TITLE
Creating pcells in gdsfactory for OpenFASOC usage

### ISSUE THREAD

**Issue by msaligane** [idea-fasoc/OpenFASOC#144]
related to https://github.com/gdsfactory/gdsfactory/issues/610

**Comment by msaligane** [comment]
@madhulikal   Please update here.

**Comment by madhulikal** [comment]
It would be helpful to have pcells created in gdsfactory for gf180 pdk. I generated some cells which can be used for the analog layout flow.
gdsfactory_gf180_pcells #201

**Comment by saicharan0112** [comment]
@alibillalhammoud isn't the gdsfactory-gen the whole idea behind creating pcells ? Can we close this @msaligane ?
