### ISSUE TITLE
Document the DLDO following the temp sense doc

### ISSUE THREAD

**Issue by msaligane** [idea-fasoc/OpenFASOC#147]
To be updated: 

- [ ] Add README to:

https://github.com/idea-fasoc/OpenFASOC/tree/main/openfasoc/generators/ldo-gen

- [ ] Add Flow Doc. here: https://openfasoc.readthedocs.io/en/latest/flow-ldo.html

Please follow: https://openfasoc.readthedocs.io/en/latest/flow-tempsense.html

- [ ] Include Notebook submitted to code-a-chip to the doc.

**Comment by msaligane** [comment]
FYI @alibillalhammoud 
Please discuss with @saicharan0112

**Comment by saicharan0112** [comment]
@lulu9312 and @alibillalhammoud is this done?

**Comment by lulu9312** [comment]
@saicharan0112 Yes.
