### ISSUE TITLE
LDO generator's work directory doesn't have any gds, spice, drc and lvs reports 

### ISSUE THREAD

**Issue by saicharan0112** [idea-fasoc/OpenFASOC#156]
LDO generator doesn't dump/copy any final gds file, spice file, drc and lvs reports similar to tempSense generator.  Dumping out the simulation png files is a good thing (which the ldo gen alone is doing among all the generators). Can we implement the same thing for tempSense generator too? 

I think it is a good idea to follow a order/pattern for all the outputs/results/reports/templates/structures across all the generators.

**Comment by msaligane** [comment]
I have been waiting on a PR from @lulu9312 for a month now.
