### ISSUE TITLE
cryo-gen only supports sky130hd, sky130hs, sky130hvl at the current stage

### ISSUE THREAD

**Issue by Jerry-lqx** [idea-fasoc/OpenFASOC#197]
As described in https://github.com/google/skywater-pdk/issues/415#issue-1650002388, one of the issues of sky130osu is the drc error of their gds.

So, sky130osu is currently not supported in cryo-gen

**Comment by saicharan0112** [comment]
@Jerry-lqx not sure if the issue got resolved at the PDK side. Is there a plan to support sky130osu now?

**Comment by Jerry-lqx** [comment]
Given that they haven't fixed the issue, I don't think I'm able to make sky130osu work.
p.s. I probably don't have time to continue with this project this semester as well.
