### ISSUE TITLE
LDO Vin range is not useful for powering sky130A standard cells

### ISSUE THREAD

**Issue by shalan** [idea-fasoc/OpenFASOC#2]
According to [this](https://github.com/idea-fasoc/OpenFASOC/blob/main/generators/ldo-gen/tools/supported_inputs.json), the LDO generator cannot generate 1.8V LDO needed to power digital macros implemented using sky130 SCLs (e.g., hd, hell, ...)

**Comment by msaligane** [comment]
That needs to be updated. FYI, the LDO has not been released yet using the open source tools.

**Comment by msaligane** [comment]
@wenbodd can you update these:
```
      "vin": {
        "max": 1.3,
        "min": 0.6}
```

**Comment by shalan** [comment]
Is it characterize for Vin beyond 1.3V? The FASoC [website](https://fasoc.engin.umich.edu/digital-ldo/) lists the same range (0.6 to 1.3V) on the LDO specs table.

**Comment by msaligane** [comment]
Yes, the sky130 version of the LDO takes in 3.3v/5v and generated 1.8v. These values from other technologies we are supporting and it seems the values were not updated.

I would advise not using this code for now. I will update this when it is ready.

**Comment by mithro** [comment]
Can you please add an example which generates something useful for SKY130?

**Comment by msaligane** [comment]
Sure. 
The temp sensor is the only thing released for now and the example is shown in the readme. LDO and SAR ADC are wip.
We should have updates around early June.

**Comment by msaligane** [comment]
This should be fixed now. @lulu9312 ?

**Comment by lulu9312** [comment]
Yes @msaligane  This is fixed. We can close this issue.
