### ISSUE TITLE
Make ldo generator simulation processing part similar to temp-sense generator

### ISSUE THREAD

**Issue by saicharan0112** [idea-fasoc/OpenFASOC#204]
@lulu9312 Currently the processing part after simulations are not modular. I can't reuse it for regression without depending on different variables and functions inside the processing.py script. Can you please keep everything inside one script so that the entire processing part is handled by just running that script?

Please refer to temp-sense generator for clear understanding.

**Comment by saicharan0112** [comment]
I don't think this will take much time. Do you think you can do this by Monday?

**Comment by lulu9312** [comment]
> I don't think this will take much time. Do you think you can do this by today?

@saicharan0112 I can get this done by tomorrow.

**Comment by saicharan0112** [comment]
https://github.com/idea-fasoc/OpenFASOC/pull/202 solves this.
