### ISSUE TITLE
Colab fails to install gdstk

### ISSUE THREAD

**Issue by seijirom** [idea-fasoc/OpenFASOC#207]
During the first step (install all tools and dependencies), colab fails to pip install gdstk as shown below:

Collecting gdstk
  Downloading gdstk-0.9.37.tar.gz (509 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 13.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from gdstk) (1.22.4)
Building wheels for collected packages: gdstk
  error: subprocess-exited-with-error
  
  × Building wheel for gdstk (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for gdstk (pyproject.toml) ... error
  ERROR: Failed building wheel for gdstk
Failed to build gdstk
ERROR: Could not build wheels for gdstk, which is required to install pyproject.toml-based projects`

**Comment by seijirom** [comment]
Thank you! It worked! Completed the whole Jupyter Notebook.

**Comment by saicharan0112** [comment]
@seijirom can you send a PR updating this inside the notebook

**Comment by saicharan0112** [comment]
@seijirom wanna send a PR?

**Comment by seijirom** [comment]
@saicharan0112 I've tried but gave up because updating code in ipynb file in my environment might cause a trouble.
I  hope someone in the team will fix the ipynb file.
Thank you.
