### ISSUE TITLE
installation procedure 

### ISSUE THREAD

**Issue by ripudamank2** [idea-fasoc/OpenFASOC#228]
Hi,
"I already have Magic, Klayout, Yosys, Openroad, and open_pdk installed on my Linux machine. How can I install this new tool without affecting my existing tools?"

**Comment by saicharan0112** [comment]
@ripudamank2 I would suggest you to start with the documentation. https://openfasoc.readthedocs.io/ Its merely cloning this repo and running the generates using the provided makefile provided under the generator

**Comment by ripudamank2** [comment]
i think your not getting my point . I already has those tool which you mentioned with OpenFASOC and i dont want to install again . 
What the procedure to just setup FASOC without installing those tool .

**Comment by msaligane** [comment]
Then you just have to run the generators and pray you have the right versions. 

The doc shared by Sai describes how to run it. Cheers.

**Comment by saicharan0112** [comment]
> i think your not getting my point . I already has those tool which you mentioned with OpenFASOC and i dont want to install again . What the procedure to just setup FASOC without installing those tool .

I still stand by my answer. Let me break it down to you. Follow the docs, check the versions supported, install conda and those respective conda versions, clone the OpenFASoC git repo, go back to the doc and read how to run the generator you are interested in and follow those instructions.
