### ISSUE TITLE
Gdsfactory-gen Improvments

### ISSUE THREAD

**Issue by alibillalhammoud** [idea-fasoc/OpenFASOC#235]
TODOs for improving gdsfactory-gen code. Feel free to add more items here: 

- [x] ReadME enhancements + add documentation content to the OpenFASOC docs
- [x] rename pygen
- [x] organize gds files in tapeout_and_RL directory
- [ ] import klayout drc code from pdk (.drc script)
- [x] publish package to pypi
- [x] comments regarding port trees
- [x] python notebook demo
- [ ] expand the existing docs directory (with the txt files)
- [x] follow up on requirements.txt: GDSFactory, sky130, and GF180 pypi packages cannot be installed at the same time without broken deps
- [x]  reformat python docustrings into markdown format for better printing in VScode

**Comment by alibillalhammoud** [comment]
@saicharan0112 @msaligane @alibillalhammoud

**Comment by alibillalhammoud** [comment]
Added comments from @harshkhandeparkar

**Comment by harshkhandeparkar** [comment]
> follow up on requirements.txt: GDSFactory, sky130, and GF180 pypi packages cannot be installed at the same time without broken deps

Elaborating on this: `gf180` and `sky130` have different version requirements of gdsfactory. sky130 requires `v7.3.0` and gf180 requires `v7.1.4`. When either package is installed, it replaces the previously installed version of gdsfactory, leading to broken dependencies. The following error is displayed on installing sky130 after gf180.

```
Successfully uninstalled gdsfactory-7.1.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gf180 0.0.3 requires gdsfactory[cad]<7.2.0,>=7.1.1, but you have gdsfactory 7.3.0 which is incompatible.
Successfully installed gdsfactory-7.3.0
```

Even though this error is displayed, the generators still seem to work.

**Comment by harshkhandeparkar** [comment]
Opened an issue in the relevant gdsfactory repo: https://github.com/gdsfactory/skywater130/issues/73.

**Comment by alibillalhammoud** [comment]
I am closing this issue and creating a new one as these tasks have been completed or deprecated
