### ISSUE TITLE
Docker build failing, can't clone ngspice github repo

### ISSUE THREAD

**Issue by chetanyagoyal** [idea-fasoc/OpenFASOC#275]
[https://github.com/idea-fasoc/OpenFASOC/actions/runs/6871911944/job/18689540074#step:4:7076](url)

@msaligane @saicharan0112

**Comment by chetanyagoyal** [comment]
Running the dockerfile build on the GCP doesnt cause any issues and ngspice compiles properly as well, this seems to be related to the workflow file itself (perhaps some changes are required there)

**Comment by saicharan0112** [comment]
Its something to do with the Github servers, nothing to do with the Dockerfile
