### ISSUE TITLE
LDO needs a reference voltage which makes the generator limited.

### ISSUE THREAD

**Issue by shalan** [idea-fasoc/OpenFASOC#3]
The LDO needs a reference voltage (not provided/generated). Given that there is no open-source VREF IP, the generated LDO cannot be used out of the box.

**Comment by msaligane** [comment]
@shalan We are working on adding that. You can use a VREF by adding a PAD for that.

**Comment by shalan** [comment]
@msaligane But if I supply the VREF externally, I can just use an external LDO. I will be waiting for the on-chip VREF.
