### ISSUE TITLE
cannot import name 'diff_pair' from 'glayout.flow.blocks'

### ISSUE THREAD

**Issue by circuitmuggle** [idea-fasoc/OpenFASOC#360]
I tried to run the glayout_opamp,ipynb in both google runtime and my local runtime.

https://colab.research.google.com/github/idea-fasoc/OpenFASOC/blob/main/docs/source/notebooks/glayout/glayout_opamp.ipynb#scrollTo=YEaPdbyc-rh2

The first two code blocks executed correctly. When I moved to the 3rd code block. (Interactive Primitive Generation in SKY130
The following cell demonstrates the different PCell and Utility generators on the Sky130 PDK.)

both runtime (google and local) report the below errors while I checked the corresponding folders are there under FASOC/openfasoc/generators/glayout/glayout/flow/blocks/elementary/diff_pair. Not sure why diff_pair cannot be imported. 

![image](https://github.com/user-attachments/assets/6dc4322b-d535-4437-bd86-a08b0d84c5b6)
![image](https://github.com/user-attachments/assets/e8014a25-53f4-4489-9d99-f62f2d0c0a28)

**Comment by circuitmuggle** [comment]
replace glayout package path from "pip install glayout" path solved the above issue, pending fix.
![image](https://github.com/user-attachments/assets/26ae4950-e313-41e2-ad85-776f3f4808c6)

**Comment by msaligane** [comment]
Thanks!
@alibillalhammoud and @harshkhandeparkar can you please review?

**Comment by circuitmuggle** [comment]
I looked at the source code and realized that maybe folder composite and elementary are for future release? Close for now as I am not sure what's the intention for next release. Easiest fix will be just add elementary back to glayout_opamp.ipynb so that it becomes

from glayout.flow.blocks.elementary import diff_pair

it will align with the rest of this git repository.

**Comment by circuitmuggle** [comment]
re-submit pull request to fix this issue https://github.com/idea-fasoc/OpenFASOC/pull/362
