### ISSUE TITLE
This flatten way may cause the LVS check problem

### ISSUE THREAD

**Issue by Elon-J** [idea-fasoc/OpenFASOC#64]
https://github.com/idea-fasoc/OpenFASOC/blob/b76b534c42759ce10d1a14714da1c8aca67484a1/openfasoc/common/drc-lvs-check/run_lvspex.sh#L5 @msaligane

**Comment by msaligane** [comment]
Thanks @Elon-J Please let me know if it works.

**Comment by saicharan0112** [comment]
Not sure if this can be helpful, but here is the PR referring to the flattening part. The CI has been failing for the flattening case - https://github.com/RTimothyEdwards/netgen/pull/45
Not clear about further details though.

**Comment by msaligane** [comment]
@Elon-J Any update on this?

**Comment by Elon-J** [comment]
Still need to be fixed, I think need to add a hierarchy check script

**Comment by msaligane** [comment]
@Elon-J any updates on this?

**Comment by Elon-J** [comment]
currently not, but we can just annotate the flatten command if we want to do the hierarchy level lvs check

**Comment by saicharan0112** [comment]
@Elon-J can we close this issue? Is it relevant anymore?

**Comment by saicharan0112** [comment]
I am closing this as this no longer looks relevant.
