### ISSUE TITLE
Updating the DLDO to latest OpenROAD

### ISSUE THREAD

**Issue by msaligane** [idea-fasoc/OpenFASOC#79]
@lulu9312

**Comment by lulu9312** [comment]
ORFS issues resolved : 

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/556
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/550
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/562

**Comment by msaligane** [comment]
Please link your PR here (and updates)

**Comment by lulu9312** [comment]
@msaligane  Yes.

**Comment by lulu9312** [comment]
Linking my forked repository here : https://github.com/lulu9312/OpenFASOC

**Comment by saicharan0112** [comment]
@lulu9312 Looks like you have updated openroad scripts for ldo already. Can we close this?

**Comment by lulu9312** [comment]
@saicharan0112 Yes we can close this.
Related PR - #110
