### ISSUE TITLE
Can not install OpenFASOC on GCP instance-4

### ISSUE THREAD

**Issue by chenliyumich** [idea-fasoc/OpenFASOC#86]
I tried to run (sudo) source ./Dependencies.sh on instance-4 and got this error message. It still doesn't work even with the -u option.
![image](https://user-images.githubusercontent.com/77688385/186303766-61e11cb8-7aaf-4044-855b-35fd9011bb75.png)

**Comment by saicharan0112** [comment]
I tried this on ld-pll machine and it is working (except the gdsfactory installation which is to do with python version update). @msaligane @chenliyumich I am not sure which machine this is.

**Comment by chenliyumich** [comment]
@saicharan0112 This is instance-4.

**Comment by saicharan0112** [comment]
@chenliyumich Thanks, I still need access to this machine. I will look at it and let you know by EOD.

**Comment by chenliyumich** [comment]
Thank you. Also, this is what I saw on instance-openfasoc-lcpll. Is this the machine you're working on?
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/77688385/186457713-6b2abbe8-0f35-41da-899d-b0d49eb66194.png">

**Comment by saicharan0112** [comment]
Yeah. That machine is having a python version which is not supported by the gdsfactory package. It requires versions atleast 3.7. I found a workaround and it is possible to install gdsfactory on that machine. https://github.com/gdsfactory/gdsfactory/issues/627

**Comment by chenliyumich** [comment]
@saicharan0112 Can you also install Magic and open_pdk globally on instance-openfasoc-lcpll? @msaligane said there's Magic installed on that machine but I could not find it.

**Comment by saicharan0112** [comment]
You can install it by yourself. Remove gdsfactory in the list inside the requirements.txt file and run the Dependencies.sh script. That should do that job in this situation,

**Comment by chenliyumich** [comment]
I still got this error on both instance-openfasoc-lcpll and instance-4
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/77688385/186498631-a30e6c7f-d031-4cc1-a801-58d4cdd9587c.png">

**Comment by saicharan0112** [comment]
I think you executed this script multiple times. It already installed miniconda3 there I guess but might not be a successful installation. Can you remove the /usr/bin/miniconda3 directory and try again? `sudo ./Dependencies.sh`

**Comment by chenliyumich** [comment]
I removed it and there's this message in the end of the installation. Is this neglectable? Is there a test that I can run after setup so that I know it is properly setup? Thank you
![image](https://user-images.githubusercontent.com/77688385/186521219-0df19fe5-7bde-46c1-83f2-806e9e36f4f8.png)

**Comment by saicharan0112** [comment]
I have never seen this kind of error TBH. This error is with the centos package installer "yum". Please ping me on openfasoc channel.

**Comment by saicharan0112** [comment]
@chenliyumich Also please share the entire error message. Just this screenshot doesn't help in understanding the error. This script installs magic, netgen, openroad, yosys, klayout and openroad binaries. Try searching for them using `which` command. Eg: `which magic`. The expected output is /usr/bin/miniconda3/bin/magic - if I am not wrong.

**Comment by chenliyumich** [comment]
@saicharan0112 I tried "which" with the tools you mentioned. For instance-4, only Magic under /usr/local/bin/magic and Klayout under /usr/bin/klayout. For instance-openfasoc-lcpll, only klayout under /usr/bin/klayout. Also, I can't "sudo source ./Dependencies.sh" in instance-openfasoc-lcpll. It would say "sudo: source: command not found
". (But I can "sudo source ./Denpendecies.sh" in instance-4)
Is there a better way to share the entire error message? The log is very long.

**Comment by chenliyumich** [comment]
@msaligane Yes. I don't know what's my next step.

**Comment by msaligane** [comment]
can you try these cmds:

```
yum install m4 tcsh libX11-devel tcl-devel tk-devel ncurses-devel bzip2 mesa-libGL-devel freeglut freeglut-devel gcc-c++ python3 make git -y
git clone git://opencircuitdesign.com/magic
cd magic
./configure
make
make install
```

**Comment by saicharan0112** [comment]
@msaligane can you add me to that instance 4 machine please? @chenliyumich I was able to run the script without any troubles on the pll machine.

**Comment by saicharan0112** [comment]
> can you try these cmds:
> 
> ```
> yum install m4 tcsh libX11-devel tcl-devel tk-devel ncurses-devel bzip2 mesa-libGL-devel freeglut freeglut-devel gcc-c++ python3 make git -y
> git clone git://opencircuitdesign.com/magic
> cd magic
> ./configure
> make
> make install
> ```
> 
> 
> 
He already got magic installed. Weird thing is it's not from miniconda3 which is the whole purpose of the script.

**Comment by saicharan0112** [comment]
@chenliyumich can you ping me on slack please?

**Comment by msaligane** [comment]
@chenliyumich Please try again the lcdpll machine, I can see magic is installed there. Please confirm if you do too.

**Comment by chenliyumich** [comment]
I ran the commands you provided on instance-openfasoc-lcpll, the magic is still installed at /usr/local/bin/magic. I am doing all the commands under /home/chenliyu/. For instance-4, the first line of the commands shows the error below: 
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/77688385/186801065-92f7b2bc-76f4-437c-ac90-1c52228d09cd.png">
@saicharan0112 I can't find you on Slack. @msaligane Can you please add us to the same channel?

**Comment by saicharan0112** [comment]
Are you on open silicon channel? The skywater ones?

**Comment by chenliyumich** [comment]
@saicharan0112 No. My name on Slack is Li-Yu Chen

**Comment by saicharan0112** [comment]
can you try this `sudo yum update`?

**Comment by chenliyumich** [comment]
I tried it on instance-4
<img width="357" alt="image" src="https://user-images.githubusercontent.com/77688385/186801583-05d19e1c-f3b9-470b-b3a8-54e5bec9b03b.png">

**Comment by msaligane** [comment]
@chenliyumich You should see an invite to the openfasoc workspace.

**Comment by saicharan0112** [comment]
Thanks for testing this script at your end @chenliyumich . I will try to get back to you on the issues we saw.
