### ISSUE TITLE
tempsense: improve routing from instances to VIN grid

### ISSUE THREAD

**Issue by luccareinehr** [idea-fasoc/OpenFASOC#87]
How it looks currently:

![image](https://user-images.githubusercontent.com/75084099/186525311-6320630e-aa6c-4dc1-ae60-33a10c19bf6d.png)

The net must be widened and must connect to the ring in multiple spots, so that its resistance is not too large, and to reduce process variation

Related: https://github.com/The-OpenROAD-Project/OpenROAD/issues/2209

**Comment by msaligane** [comment]
Please link the related GitHub issues in OpenROAD here so we are able to track this.

**Comment by luccareinehr** [comment]
Addressed by #112 and #113
