### ISSUE TITLE
tempsense: manual place of header insts results in overlapping tap cells

### ISSUE THREAD

**Issue by luccareinehr** [idea-fasoc/OpenFASOC#90]
Header cells are large enough that manual placement with the `customPlace_east` procedure makes them overlap with the tap cells in the design, failing placement checks (and thus, the flow).

(header cell highlighted)
![image](https://user-images.githubusercontent.com/75084099/186729553-05041301-8488-4c2e-8c9c-a73d41b6f726.png)

(overlapping tap cell highlighted)
![image](https://user-images.githubusercontent.com/75084099/186729585-bdaa2e1c-e365-4f04-981c-1854b7687518.png)

This happens when manual placement is done **before `tapcell` is called and also after**.

**Comment by msaligane** [comment]
We should have multiple versions of these header cells (different sizing, and different layouts). That would increase DSE options and probably improve results. 

Another point is that we could use differential inverters in the subthreshold ROs. Or other topologies.

**Comment by luccareinehr** [comment]
Related: https://github.com/The-OpenROAD-Project/OpenROAD/issues/2210

**Comment by luccareinehr** [comment]
Closed by #111
